CounterFrontend/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace CounterFrontend.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

CounterFrontend/Pages/Index.cshtml.cs
using Dapr.Client;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using static System.Net.WebRequestMethods;

namespace CounterFrontend.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IHttpClientFactory _httpClientFactory;

        public int Count { get; private set; }

        public IndexModel(ILogger<IndexModel> logger, IHttpClientFactory httpClientFactory)
        {
            _logger = logger;
            _httpClientFactory = httpClientFactory;
        }

        public async Task OnGet()
        {
            var client = _httpClientFactory.CreateClient("counter-api");
            Count = await client.GetFromJsonAsync<int>("count");
        }

        public async Task<IActionResult> OnPostWithHttpClientAsync()
        {
            var client = _httpClientFactory.CreateClient("counter-api");
            _ = await client.PostAsync("count/increment", null);
            return RedirectToPage("./Index");
        }

        public async Task<IActionResult> OnPostWithDaprClientAsync()
        {
            using var client = new DaprClientBuilder().Build();
            var methodRequest = client.CreateInvokeMethodRequest(HttpMethod.Post, "counter-api", "count/increment");
            await client.InvokeMethodAsync(methodRequest);
            return RedirectToPage("./Index");
        }
    }
}

CounterFrontend/Pages/PublishMessage.cshtml.cs
using Dapr.Client;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json.Serialization;

namespace CounterFrontend.Pages
{
    public class PublishMessageModel : PageModel
    {
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            using var client = new DaprClientBuilder().Build();

            // Publish an event/message using Dapr PubSub
            await client.PublishEventAsync("pubsub", "counts", new CountEvent(10));
            return RedirectToPage("./Index");
        }

        public record CountEvent([property: JsonPropertyName("amount")] int Amount);

    }
}

CounterFrontend/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    Current count:
    <h1 class="display-4">@Model.Count</h1>
    <p>
    things    
    </p>

    <form method="post">
        <input asp-page-handler="WithHttpClient" type="submit" value="Increment count using HTTP Client" />
    </form>

    <form method="post">
        <input asp-page-handler="WithDaprClient" type="submit" value="Increment count using Dapr Client" />
    </form>
</div>

CounterFrontend/Pages/PublishMessage.cshtml
@page
@model CounterFrontend.Pages.PublishMessageModel
@{
    ViewData["Title"] = "Publish message";
}

<div class="text-center">
    <form method="post">
        <input type="submit" value="Publish +10 increment message"  />
    </form>
</div>

CounterFrontend/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CounterFrontend</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CounterFrontend.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CounterFrontend</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/PublishMessage">Publish message</a>
                        </li>
                    </ul>           
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CounterFrontend - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>